import { QueryInterface } from 'sequelize';

export async function up(queryInterface: QueryInterface) {
  await queryInterface.bulkInsert(
    'permissions',
    [
      {
        name: 'users_read',
        description: 'Leitura de usuário',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'users_create',
        description: 'Criação de usuário',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'users_update',
        description: 'Atualização de usuário',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'users_delete',
        description: 'Deleção de usuário',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'deleted_users_read',
        description: 'Ver usuários deletados',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'restore_users',
        description: 'Restaurar Usuários',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'users_purge',
        description: 'Deleção de usuário',
        group: 'users',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'roles_read',
        description: 'Ver perfis',
        group: 'roles',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'roles_create',
        description: 'Criar perfis',
        group: 'roles',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'roles_update',
        description: 'Alterar Perfis',
        group: 'roles',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'roles_delete',
        description: 'Deletar perfis',
        group: 'roles',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'permission_read',
        description: 'Ler permissões',
        group: 'permissions',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'permission_create',
        description: 'Salvar permissões',
        group: 'permissions',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'type_products',
        description: 'Listar os produtos',
        group: 'type',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ARGOX
      {
        name: 'ARGOX_read',
        description: 'Ver produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ARGOX_create',
        description: 'Criar produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ARGOX_delete',
        description: 'Deletar produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ARGOX_update',
        description: 'Atualizar produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ARGOX_import',
        description: 'Importar produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ARGOX_export',
        description: 'Exportar produtos argox',
        group: 'ARGOX',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // DATALOGIC
      {
        name: 'DATALOGIC_read',
        description: 'Ver produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DATALOGIC_create',
        description: 'Criar produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DATALOGIC_update',
        description: 'Atualizar produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DATALOGIC_delete',
        description: 'Deletar produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DATALOGIC_import',
        description: 'Importar produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DATALOGIC_export',
        description: 'Exportar produtos datalogic',
        group: 'DATALOGIC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // DIMEP
      {
        name: 'DIMEP_read',
        description: 'Ver produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DIMEP_create',
        description: 'Criar produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DIMEP_update',
        description: 'Atualizar produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DIMEP_delete',
        description: 'Deletar produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DIMEP_import',
        description: 'Importar produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DIMEP_export',
        description: 'Exportar produtos dimep',
        group: 'DIMEP',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ELGIN-BEMATECH
      {
        name: 'ELGIN-BEMATECH_read',
        description: 'Ver produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELGIN-BEMATECH_create',
        description: 'Criar produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELGIN-BEMATECH_update',
        description: 'Atualizar produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELGIN-BEMATECH_delete',
        description: 'Deletar produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELGIN-BEMATECH_import',
        description: 'Importar produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELGIN-BEMATECH_export',
        description: 'Exportar produtos elgin bematech',
        group: 'ELGIN_BEMATECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ELO
      {
        name: 'ELO_read',
        description: 'Ver produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELO_create',
        description: 'Criar produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELO_update',
        description: 'Atualizar produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELO_delete',
        description: 'Deletar produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELO_import',
        description: 'Importar produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ELO_export',
        description: 'Exportar produtos elo',
        group: 'ELO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // EPSON
      {
        name: 'EPSON_read',
        description: 'Ver produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EPSON_create',
        description: 'Criar produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EPSON_update',
        description: 'Atualizar produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EPSON_delete',
        description: 'Deletar produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EPSON_import',
        description: 'Importar produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EPSON_export',
        description: 'Exportar produtos epson',
        group: 'EPSON',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // GERBO
      {
        name: 'GERBO_read',
        description: 'Ver produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERBO_create',
        description: 'Criar produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERBO_update',
        description: 'Atualizar produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERBO_delete',
        description: 'Deletar produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERBO_import',
        description: 'Importar produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERBO_export',
        description: 'Exportar produtos gerbo',
        group: 'GERBO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // GERTEC
      {
        name: 'GERTEC_read',
        description: 'Ver produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERTEC_create',
        description: 'Criar produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERTEC_update',
        description: 'Atualizar produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERTEC_delete',
        description: 'Deletar produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERTEC_import',
        description: 'Importar produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GERTEC_export',
        description: 'Exportar produtos gertec',
        group: 'GERTEC',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // GTS
      {
        name: 'GTS_read',
        description: 'Ver produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GTS_create',
        description: 'Criar produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GTS_update',
        description: 'Atualizar produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GTS_delete',
        description: 'Deletar produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GTS_import',
        description: 'Importar produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'GTS_export',
        description: 'Exportar produtos gts',
        group: 'GTS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // HONEYWELL
      {
        name: 'HONEYWELL_read',
        description: 'Ver produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'HONEYWELL_create',
        description: 'Criar produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'HONEYWELL_update',
        description: 'Atualizar produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'HONEYWELL_delete',
        description: 'Deletar produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'HONEYWELL_import',
        description: 'Importar produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'HONEYWELL_export',
        description: 'Exportar produtos honeywell',
        group: 'HONEYWELL',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // LOGIC-CONTROLS
      {
        name: 'LOGIC-CONTROLS_read',
        description: 'Ver produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'LOGIC-CONTROLS_create',
        description: 'Criar produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'LOGIC-CONTROLS_update',
        description: 'Atualizar produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'LOGIC-CONTROLS_delete',
        description: 'Deletar produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'LOGIC-CONTROLS_import',
        description: 'Importar produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'LOGIC-CONTROLS_export',
        description: 'Exportar produtos logic controls',
        group: 'LOGIC_CONTROLS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // MENNO
      {
        name: 'MENNO_read',
        description: 'Ver produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MENNO_create',
        description: 'Criar produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MENNO_update',
        description: 'Atualizar produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MENNO_delete',
        description: 'Deletar produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MENNO_import',
        description: 'Importar produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MENNO_export',
        description: 'Exportar produtos menno',
        group: 'MENNO',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // MONUS
      {
        name: 'MONUS_read',
        description: 'Ver produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MONUS_create',
        description: 'Criar produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MONUS_update',
        description: 'Atualizar produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MONUS_delete',
        description: 'Deletar produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MONUS_import',
        description: 'Importar produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MONUS_export',
        description: 'Exportar produtos monus',
        group: 'MONUS',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // POSTECH
      {
        name: 'POSTECH_read',
        description: 'Ver produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'POSTECH_create',
        description: 'Criar produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'POSTECH_update',
        description: 'Atualizar produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'POSTECH_delete',
        description: 'Deletar produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'POSTECH_import',
        description: 'Importar produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'POSTECH_export',
        description: 'Exportar produtos postech',
        group: 'POSTECH',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // TANCA
      {
        name: 'TANCA_read',
        description: 'Ver produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TANCA_create',
        description: 'Criar produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TANCA_update',
        description: 'Atualizar produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TANCA_delete',
        description: 'Deletar produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TANCA_import',
        description: 'Importar produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'TANCA_export',
        description: 'Exportar produtos tanca',
        group: 'TANCA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ZEBRA
      {
        name: 'ZEBRA_read',
        description: 'Ver produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ZEBRA_create',
        description: 'Criar produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ZEBRA_update',
        description: 'Atualizar produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ZEBRA_delete',
        description: 'Deletar produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ZEBRA_import',
        description: 'Importar produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ZEBRA_export',
        description: 'Exportar produtos zebra',
        group: 'ZEBRA',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      //Banners
      {
        name: 'banners_read',
        description: 'Leitura de banners',
        group: 'banners',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'banners_update',
        description: 'Atualização de banners',
        group: 'banners',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'banners_reorder',
        description: 'Reordenação de banners',
        group: 'banners',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'banners_create',
        description: 'Criação de banners',
        group: 'banners',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'banners_delete',
        description: 'Deleção de banners',
        group: 'banners',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {},
  );
}
export async function down(queryInterface: QueryInterface) {
  await queryInterface.bulkDelete('permissions', {});
}
