import getDate from '@app/src/Shared/Infrastructure/Utils/Date';
import { QueryInterface } from 'sequelize';

export async function up(queryInterface: QueryInterface) {
  await queryInterface.bulkInsert(
    'permissions',
    [
      {
        name: 'users_read',
        description: 'Ver usuário',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'users_create',
        description: 'Criar usuário',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'users_update',
        description: 'Atualizar usuário',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'users_delete',
        description: 'Deletar usuário',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'deleted_users_read',
        description: 'Ver usuários deletados',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'restore_users',
        description: 'Restaurar Usuários',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'users_purge',
        description: 'Deletar usuário',
        group: 'Usuários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'acl_read',
        description: 'Ver perfis',
        group: 'Papéis e Permissões',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'acl_create',
        description: 'Criar perfis',
        group: 'Papéis e Permissões',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'acl_update',
        description: 'Alterar Perfis',
        group: 'Papéis e Permissões',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'acl_delete',
        description: 'Excluir perfis',
        group: 'Papéis e Permissões',
        created_at: new Date(),
        updated_at: new Date(),
      },
      //Banners
      {
        name: 'banners_read',
        description: 'Ver banners',
        group: 'Banners',
        created_at: getDate(),
        updated_at: getDate(),
      },
      {
        name: 'banners_update',
        description: 'Atualizar banners',
        group: 'Banners',
        created_at: getDate(),
        updated_at: getDate(),
      },
      {
        name: 'banners_reorder',
        description: 'Reordenação de banners',
        group: 'Banners',
        created_at: getDate(),
        updated_at: getDate(),
      },
      {
        name: 'banners_create',
        description: 'Criar banners',
        group: 'Banners',
        created_at: getDate(),
        updated_at: getDate(),
      },
      {
        name: 'banners_delete',
        description: 'Deletar banners',
        group: 'Banners',
        created_at: getDate(),
        updated_at: getDate(),
      },
      {
        name: 'brands_read',
        description: 'Ver Marca',
        group: 'Marcas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'brands_create',
        description: 'Criar Marca',
        group: 'Marcas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'brands_update',
        description: 'Atualizar Marca',
        group: 'Marcas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'brands_delete',
        description: 'Deletar Marca',
        group: 'Marcas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'categories_read',
        description: 'Ver Categoria',
        group: 'Categorias',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'categories_create',
        description: 'Criar Categoria',
        group: 'Categorias',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'categories_update',
        description: 'Atualizar Categoria',
        group: 'Categorias',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'categories_delete',
        description: 'Deletar Categoria',
        group: 'Categorias',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'customers_read',
        description: 'Ver Cliente',
        group: 'Clientes',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'customers_create',
        description: 'Criar Cliente',
        group: 'Clientes',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'customers_update',
        description: 'Atualizar Cliente',
        group: 'Clientes',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'customers_delete',
        description: 'Deletar Cliente',
        group: 'Clientes',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'employees_read',
        description: 'Ver Funcionário',
        group: 'Funcionários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'employees_create',
        description: 'Criar Funcionário',
        group: 'Funcionários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'employees_update',
        description: 'Atualizar Funcionário',
        group: 'Funcionários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'employees_delete',
        description: 'Deletar Funcionário',
        group: 'Funcionários',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'suppliers_read',
        description: 'Ver Fornecedor',
        group: 'Fornecedores',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'suppliers_create',
        description: 'Criar Fornecedor',
        group: 'Fornecedores',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'suppliers_update',
        description: 'Atualizar Fornecedor',
        group: 'Fornecedores',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'suppliers_delete',
        description: 'Deletar Fornecedor',
        group: 'Fornecedores',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'products_read',
        description: 'Ver Produto',
        group: 'Produtos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'products_create',
        description: 'Criar Produto',
        group: 'Produtos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'products_update',
        description: 'Atualizar Produto',
        group: 'Produtos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'products_delete',
        description: 'Deletar Produto',
        group: 'Produtos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'products_export',
        description: 'Exportar de Produto',
        group: 'Produtos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'sales_read',
        description: 'Ver Venda',
        group: 'Vendas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'sales_create',
        description: 'Criar Venda',
        group: 'Vendas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'sales_update',
        description: 'Atualizar Venda',
        group: 'Vendas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'sales_delete',
        description: 'Deletar Venda',
        group: 'Vendas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'sales_export',
        description: 'Exportar de Venda',
        group: 'Vendas',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'orders_read',
        description: 'Ver Pedido',
        group: 'Pedidos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'orders_create',
        description: 'Criar Pedido',
        group: 'Pedidos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'orders_update',
        description: 'Atualizar Pedido',
        group: 'Pedidos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'orders_delete',
        description: 'Deletar Pedido',
        group: 'Pedidos',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'orders_export',
        description: 'Exportar de Pedido',
        group: 'Pedidos',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
    {},
  );
}
export async function down(queryInterface: QueryInterface) {
  await queryInterface.bulkDelete('permissions', {});
}
