version: '3.5'

services:
    mens_database:
        container_name: mens_database
        build:
            context: ../../
            dockerfile: .docker/staging/postgres/Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/scripts:/etc/postgresql/scripts
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: on-failure
        tty: true

    mens_redis:
        container_name: mens_redis
        build:
            context: ../../
            dockerfile: .docker/local/redis/Dockerfile
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./redis/data:/data
        restart: on-failure
        tty: true

    mens_api:
        container_name: mens_api
        build:
            context: ../../
            dockerfile: .docker/staging/node/Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        restart: on-failure
        environment:
            NODE_OPTIONS: ${NODE_OPTIONS}
        ports:
            - "${API_PORT}:3333"
        working_dir: /var/www/mens-api
        volumes:
            - ../../:/var/www/mens-api
        tty: true
        links:
            - mens_database
            - mens_redis
        networks:
            mens_network:
                ipv4_address: 172.19.0.4

networks:
  mens_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1