version: "3.5"

services:
    mens_database:
        container_name: mens_database
        build:
            context: ../../
            dockerfile: .docker/staging/postgres/Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/scripts:/etc/postgresql/scripts
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: on-failure
        tty: true

    mens_redis:
        container_name: mens_redis
        build:
            context: ../../
            dockerfile: .docker/local/redis/Dockerfile
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./redis/data:/data
        restart: on-failure
        tty: true

    mens_api:
        container_name: mens_api
        build:
            context: ../../
            dockerfile: .docker/staging/node/Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        restart: on-failure
        environment:
            NODE_OPTIONS: ${NODE_OPTIONS}
        ports:
            - "${API_PORT}:3333"
        working_dir: /var/www/mens-api
        volumes:
            - ../../:/var/www/mens-api
        tty: true
        links:
            - mens_database
            - mens_redis
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        container_name: jenkins
        privileged: true
        user: root
        ports:
            - 8081:8080
            - 50000:50000
        environment:
            - DOCKER_HOST=/var/run/docker.sock
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
            - JENKINS_HOME=/var/jenkins_home
        volumes:
            - /var/jenkins/caches:/var/jenkins/caches
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/jenkins_home:/var/jenkins_home


networks:
    default:
        name: mens_network
